#!/usr/bin/env bash

: "${PUBLIC_BASE_DOMAIN:?PUBLIC_BASE_DOMAIN is required}"

ADMIN_HOST="${ADMIN_HOST:-admin.${PUBLIC_BASE_DOMAIN}}"
AUTH_HOST="${AUTH_HOST:-auth.${PUBLIC_BASE_DOMAIN}}"
REGISTER_HOST="${REGISTER_HOST:-register.${PUBLIC_BASE_DOMAIN}}"
export ADMIN_HOST AUTH_HOST REGISTER_HOST
